[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m venv venv",
  "venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "node server/index.js"
